name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: build_job
    displayName: Build Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: true
    # Add any build-related steps here

- stage: ManualApprovalAfterBuild
  displayName: Manual Approval After Build
  dependsOn: Build
  jobs:  
  - job: waitForValidation
    displayName: Wait for external validation  
    pool: server    
    timeoutInMinutes: 10 # job times out in 10 minutes
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 5 # task times out in 5 minutes
      inputs:
        notifyUsers: |
          vishwanatham.male@gmail.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'

- stage: DeployToStaging
  displayName: Deploy to Staging Stage
  dependsOn: ManualApprovalAfterBuild
  jobs:
  - job: deploy_to_staging_job
    displayName: Deploy to Staging Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(deployment_token)
        app_location: "/" # Specify the source code path
        api_location: "" # Api source code path - optional
        output_location: "dist" # Built app content directory - optional
        deployment_environment: 'staging' # Specify the deployment environment as staging
